// src/shared/models.rs (or a new menu_models.rs file)

use serde::{Deserialize, Serialize};
use sqlx::FromRow;


#[derive(Debug, FromRow, Serialize, Deserialize, Clone)]
pub struct MenuItem {
    pub menu_id: i32,
    pub papa_id: Option<i32>,
    pub nombre: String,
    pub codigo_permiso: String,
    pub tipo_elemento: String,
    pub segmento_ruta: String,
    pub ruta: String,
    pub orden: i32,
    pub autor: String,
    pub fecha_creacion: String, // Usa un tipo de dato de fecha/hora más preciso
    pub modificado_por: Option<String>,
    pub fecha_modificacion: Option<String>,
}



#[derive(Debug, Serialize, Deserialize)]
pub struct NewMenuItem {
    pub papa_id: Option<i32>,
    pub aplicativo_id: i32,
    pub nombre: String,
    pub codigo_permiso: String,
    pub tipo_elemento: String,
    pub segmento_ruta: String,
    // Note: 'ruta' will be generated by the backend, but we can accept it for simplicity or validation
    pub orden: i32,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct UpdateMenuItem {
    pub nombre: Option<String>,
    pub codigo_permiso: Option<String>,
    pub tipo_elemento: Option<String>,
    pub segmento_ruta: Option<String>,
    pub orden: Option<i32>,
}